version: '3'
services:
  mariadb:
    image: mariadb:custom
    build:
      context: ./requirements/mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MARIADB_DATABASE}
      - MYSQL_USER=${MARIADB_USER}
      - MYSQL_PASSWORD=${MARIADB_PASSWORD}
    volumes:
      - data-db:/var/lib/mariadb
    networks:
      - docker-network
    ports:
      - "3306:3306"
    restart: always

  wordpress:
    image: wordpress:custom
    build:
      context: ./requirements/wordpress # WordPress用のDockerfileがあるディレクトリを指定
    ports:
      - "9000:80"
    environment:
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - WORDPRESS_DB_NAME=${MARIADB_DATABASE}
      - WORDPRESS_DB_USER=${MARIADB_USER}
      - WORDPRESS_DB_PASSWORD=${MARIADB_PASSWORD}
    volumes:
      - data-wp:/var/www/html/wp
    networks:
      - docker-network
    restart: always
    depends_on:
      - mariadb

  nginx:
    image: nginx:custom
    build:
      context: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - data-wp:/var/www/html/wp
    networks:
      - docker-network
    restart: always
    depends_on:
      - wordpress

networks:
  docker-network:

volumes:
  data-db:
    driver: local
    driver_opts:
      type: none       # "none" => ローカルディレクトリを使用
      o: bind          # "bind" => 実体ディレクトリをバインド
      device: ${PATH_DATA}db    # 実体path
  data-wp:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PATH_DATA}wp
