version: '3.8'
services:
  mariadb:
    image: mariadb:42_inception
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    env_file:
      .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MARIADB_DATABASE}
      - MYSQL_USER=${MARIADB_USER}
      - MYSQL_PASSWORD=${MARIADB_PASSWORD}
    volumes:
      - ./requirements/mariadb/conf/mariadb.cnf:/etc/mysql/mariadb.cnf
      - ./requirements/mariadb/conf/50-server.cnf:/etc/mysql/mariadb.conf.d/50-server.cnf
      - data-db:/var/lib/mysql
    networks:
      - docker-network
    restart: always

  wordpress:
    image: wordpress:42_inception
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    ports:
      - "9000:80"
    env_file:
      .env
    environment:
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - DOMAIN_NAME=${DOMAIN_NAME}
      - WORDPRESS_TITLE=${WORDPRESS_TITLE}
      - WORDPRESS_ADMIN_USER=${WORDPRESS_ADMIN_USER}
      - WORDPRESS_ADMIN_PASSWORD=${WORDPRESS_ADMIN_PASSWORD}
      - WORDPRESS_ADMIN_EMAIL=${WORDPRESS_ADMIN_EMAIL}
      - WORDPRESS_ADMIN_USER2=${WORDPRESS_ADMIN_USER2}
      - WORDPRESS_ADMIN_PASSWORD2=${WORDPRESS_ADMIN_PASSWORD2}
    volumes:
      - ./requirements/wordpress/conf/www.conf:/etc/php/8.2/fpm/pool.d/www.conf
      - ./requirements/wordpress/conf/php-fpm.conf:/etc/php/8.2/fpm/php-fpm.conf
      - data-wp:/var/www/html/wordpress
    networks:
      - docker-network
    restart: always
    depends_on:
      - mariadb
#      mariadb:
#        condition: service_healthy

  nginx:
    image: nginx:42_inception
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
      - "5173:5173"
    env_file:
      .env
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    volumes:
      - ./requirements/nginx/conf/default.conf:/etc/nginx/sites-enabled/default
      - ./requirements/nginx/conf/static.conf:/etc/nginx/conf.d/static.conf
      - ./requirements/nginx/tools/ssl:/etc/nginx/ssl
      - data-wp:/var/www/html/wordpress
      - data-staticsite:/var/www/html/staticsite
    networks:
      - docker-network
    restart: always
    depends_on:
      - mariadb
      - wordpress

#  redis:
#    image: redis:42_inception
#    build:
#      context: ./requirements/bonus/redis
#      dockerfile: Dockerfile
#    ports:
#      - "6379:6379"
#    networks:
#      - docker-network
#    restart: always
#    depends_on:
#      - mariadb
#      - wordpress

  # ftp:
  #   image: ftp:42_inception
  #   build:
  #     context: ./requirements/bonus/ftp
  #     dockerfile: Dockerfile
  #   ports:
  #     - "21:21"
  #   networks:
  #     - docker-network
  #   restart: always
  #   depends_on:
  #     - mariadb
  #     - wordpress

  adminer:
    image: adminer:42_inception
    build:
      context: ./requirements/bonus/adminer
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - docker-network
    restart: always
    depends_on:
      - mariadb
      - wordpress
      - nginx

  # ファイルをvolumeに設置するだけのコンテナ
  staticsite:
    image: staticsite:42_inception
    build:
      context: ./requirements/bonus/staticsite
      dockerfile: Dockerfile
    volumes:
      - data-staticsite:/usr/share/nginx/html

networks:
  docker-network:

volumes:
  data-db:
    driver: local
  data-wp:
    driver: local
  data-staticsite:
    driver: local
