version: '3.8'
services:
  mariadb:
    image: mariadb:42_inception
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    env_file:
      .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MARIADB_DATABASE}
      - MYSQL_USER=${MARIADB_USER}
      - MYSQL_PASSWORD=${MARIADB_PASSWORD}
    volumes:
      - ./requirements/mariadb/conf/mariadb.cnf:/etc/mysql/mariadb.cnf
      - data-db:/var/lib/mariadb
    networks:
      - docker-network
    restart: always

  wordpress:
    image: wordpress:42_inception
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    ports:
      - "9000:80"
    env_file:
      .env
    environment:
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - WORDPRESS_DB_NAME=${MARIADB_DATABASE}
      - WORDPRESS_DB_USER=${MARIADB_USER}
      - WORDPRESS_DB_PASSWORD=${MARIADB_PASSWORD}
    volumes:
      - data-wp:/var/www/html/wp
    networks:
      - docker-network
    restart: always
    depends_on:
      - mariadb
#      mariadb:
#        condition: service_healthy

  nginx:
    image: nginx:42_inception
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    volumes:
      - data-wp:/var/www/html/wp
    networks:
      - docker-network
    restart: always
    depends_on:
      - mariadb
      - wordpress
#      mariadb:
#        condition: service_healthy
#      wordpress:
#        condition: service_healthy

networks:
  docker-network:

volumes:
  data-db:
    driver: local
  data-wp:
    driver: local
